# Generated by Django 5.0.4 on 2024-04-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='setting',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
